import { Geist, Geist_Mono } from "next/font/google"; // default import
import "./globals.css";// default import
import Link from "next/link"; // added link import from next.js for navigation between pages

// default
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
// default 
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
// default =
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Navbar function for navigation amoung all pages in application
function Navbar() {
  return (
    // The header element serves as the main container for the navigation bar
    <header className="bg-blue-100 py-5">
    {/* The div container ensures that the content is centered and responsive */}
    <div className="container mx-auto">
      {/* The nav element provides the structure for the navigation links */}
      <nav className="flex items-center justify-between">

        {/* First navigation link: Home */}
        <div className="flex items-center">
          {/* Link component to navigate to the home page; includes styling for font size, color, and hover effect */}
          <Link href="/" className="font-bold text-2xl text-gray-700 hover:text-gray-900 text-decoration-none">HOME</Link>
        </div>

        {/* Second navigation link: Course Catalog */}
        <div className="flex items-center">
          {/* Link component to navigate to the courses catalog */}
          <Link href="/courses" className="font-bold text-2xl text-gray-700 hover:text-gray-900 text-decoration-none">COURSE CATALOG</Link>
        </div>

        {/* Third navigation link: LOGIN*/}
        <div>
          {/* Link component to login to account */}
          <Link href="/login" className="font-bold text-2xl text-gray-700 hover:text-gray-900 text-decoration-none border border-primary rounded p-2 hover:text-gray-900 hover:bg-white">LOGIN</Link>
        </div>


      </nav>

    </div>
  </header>
  );
}
// RootLayout function by default 
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar /> {/* add Navbar component to render on ALL pages */}
        {children}
      </body>
    </html>
  );
}
